### ISSUE TITLE
I can't save in mp3 format

### ISSUE THREAD

**Issue by EvilMis** [poetaster/harbour-audiocut#10]
Audiocut version 1.4.3.
Saving in other formats works. Lame is present and working (at least from the command line).
An error appears in the log while saving in mp3:
```
paź 19 16:08:02 Xperia10III sailfish-qml[7201]: [D] unknown:0 - "PyOtherSide error: Traceback (most recent call last):\n\n  File \"/usr/share/harbour-audiocut/qml/py/audiox.py\", line 105, in saveFile\n    subprocess.run([ \"lame\", mp3CompressBitrateType, \"--tt\", str(tagTitle), \"--ta\", str(tagArtist), \"--tl\", str(tagAlbum), \"--ty\", str(tagDate), \"--tn\", str(tagTrack), \"/\"+outputPathTmp, \"/\"+savePath ])\n\n  File \"/usr/lib64/python3.8/subprocess.py\", line 493, in run\n    with Popen(*popenargs, **kwargs) as process:\n\n  File \"/usr/lib64/python3.8/subprocess.py\", line 858, in __init__\n    self._execute_child(args, executable, preexec_fn, close_fds,\n\n  File \"/usr/lib64/python3.8/subprocess.py\", line 1704, in _execute_child\n    raise child_exception_type(errno_num, err_msg, err_filename)\n\nPermissionError: [Errno 13] Access denied: 'lame'\n"
```

**Comment by poetaster** [comment]
Yeah, I noticed this again recently. I haven't got a current version of lame built but I think you could try it by disabling sandboxing.
[X-Sailjail]
Sandboxing=Disabled

```
In /usr/share/applications/harbour-audiocut.desktop

You can place a copy of that file in /etc/sailjail/applications and it won't be overwritten. If that works. It should work, though. Thanks!

**Comment by EvilMis** [comment]
Thank you for your help. After this modification it works.
The compiled lame in the latest version is here [https://download.opensuse.org/ports/aarch64/distribution/leap/15.4/repo/oss/aarch64/lame-3.100-1.33.aarch64.rpm](url)

**Comment by poetaster** [comment]
> Thank you for your help. After this modification it works. The compiled lame in the latest version is here [https://download.opensuse.org/ports/aarch64/distribution/leap/15.4/repo/oss/aarch64/lame-3.100-1.33.aarch64.rpm](url)

With nephros help, I've pushed lame 3.100 to chum.
